### ISSUE TITLE
Unable to run evaluation

### ISSUE THREAD

**Issue by thomasw21** [bigscience-workshop/Megatron-DeepSpeed#176]
When running this script https://github.com/bigscience-workshop/bigscience/blob/master/train/tr9-glu/tr9c-1B3-swiglu-pile.slurm , got the following error:

```
Traceback (most recent call last):
  File "/gpfsscratch/rech/six/commun/checkpoints/tr9c-1B3-swiglu-pile/code/Megatron-DeepSpeed/pretrain_gpt.py", line 268, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/gpfsssd/scratch/rech/six/commun/checkpoints/tr9c-1B3-swiglu-pile/code/Megatron-DeepSpeed/megatron/training.py", line 181, in pretrain
    iteration = train(forward_step_func,
  File "/gpfsssd/scratch/rech/six/commun/checkpoints/tr9c-1B3-swiglu-pile/code/Megatron-DeepSpeed/megatron/training.py", line 810, in train
    names = names if names is not None else ['valid'] * len(valid_data_iterator)
TypeError: object of type 'NoneType' has no len()
```

It trained well until reaching the evaluation. 

Looks related to https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/97

cc @hadyelsahar  @TevenLeScao

**Comment by thomasw21** [comment]
More infos:
 - I could reproduce with 2 gpus only when tweaking `get_3d_dimensions` by putting `tp==2` instead. https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/tests/test_training.py#L53-L54
 - One of the reasons why this fails is that not all ranks have access to dataloaders, typically on `tp_rank == 0` do have access to them https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/main/megatron/training.py#L984-L1039

**Comment by hadyelsahar** [comment]
It looks indeed related to #PR97 I'll take a look on this by Friday.

**Comment by thomasw21** [comment]
I think this was fixed with https://github.com/bigscience-workshop/Megatron-DeepSpeed/commit/b982e040fbf12f089115cde560f685f673de6eb1 .

I think one of the reasons we didn't see this coming was you have to run tests with 4 gpus wight now to have TP > 1. Maybe we should improve tests to have TP>1 for 2 gpus, ie testing for both TP=1/PP=2 and TP=2/PP=1 (we only do the first). Would you be interested in improving the tests for that?

**Comment by TevenLeScao** [comment]
Sorry, hotfixed last night, should have documented. Also think the double testing would be nice and not too hard.

**Comment by thomasw21** [comment]
Related to #178
