### ISSUE TITLE
c10d crashes on `sys.exit(0)`

### ISSUE THREAD

**Issue by stas00** [bigscience-workshop/Megatron-DeepSpeed#265]
When not using
```
export CUDA_LAUNCH_BLOCKING=1
```

on normal program exit I get:

```
[exiting program at iteration 6] datetime: 2022-03-11 15:20:26 
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: driver shutting down
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from query at /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f87dd253d62 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x11a (0x7f882f0207ba in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x50 (0x7f882f022ab0 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x11c (0x7f882f02357c in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: <unknown function> + 0xc9039 (0x7f8889cb9039 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f88aa8a3609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f88aa7c8163 in /lib/x86_64-linux-gnu/libc.so.6)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 653490) of binary: /home/stas/anaconda3/envs/py38-pt110/bin/python
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 732, in <module>
    main()
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 728, in main
    run(args)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in run
    elastic_launch(
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

with pt-1.10 and pt-1.11

happens on my home setup and JeanZay too

adding `export CUDA_LAUNCH_BLOCKING=1` most of the time removes the problem instead of giving the trace.

The exit code where it fails is here:

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/497aa1bfd3b817ff63e985bd15abe65d1cef45d9/megatron/training.py#L931-L933

I tried to emulate the end of the program with:

```
import sys, os, torch
import torch.distributed as dist

local_rank = int(os.environ["LOCAL_RANK"])
torch.cuda.set_device(local_rank)
device = torch.device("cuda", local_rank)

dist.init_process_group("nccl")
dist.all_reduce(torch.ones(1).to(device), op=dist.ReduceOp.SUM)
dist.barrier()

if local_rank == 0:
    print(f"exiting")

sys.exit()
```
and then running 
```
python -u -m torch.distributed.run --nproc_per_node 2 --nnodes 1 --rdzv_endpoint localhost:6777 --rdzv_backend c10d --max_restarts 0 exit.py
````
but it doesn't fail.

Perhaps because I need to do some more operations or run deepspeed - the whole program is a way too complex to try to reproduce it with a simple script.

The launch script that crashes:
```
CHECKPOINT_PATH=checkpoints/gpt2

VOCAB_FILE=data/gpt2-vocab.json
MERGE_FILE=data/gpt2-merges.txt
DATA_PATH=data/oscar-en-10k/meg-gpt2_text_document
TENSORBOARD_PATH=output_dir/tensorboard

N_GPUS=2
MICRO_BATCH_SIZE=4
GLOBAL_BATCH_SIZE=16
TP_SIZE=1
PP_SIZE=2

NLAYERS=1
NHIDDEN=8
NHEADS=2
SEQ_LEN=8
VOCAB_SIZE=50257

SAVE_INTERVAL=50

TRAIN_SAMPLES=50_000

GPT_ARGS=" \
    --num-layers $NLAYERS \
    --hidden-size $NHIDDEN \
    --num-attention-heads $NHEADS \
    --seq-length $SEQ_LEN \
    --max-position-embeddings $SEQ_LEN \
    --micro-batch-size $MICRO_BATCH_SIZE \
    --rampup-batch-size 4 4 1_000 \
    --global-batch-size $GLOBAL_BATCH_SIZE \
    --train-samples $TRAIN_SAMPLES \
    --optimizer adam \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-8 \
    --lr 1e-4 \
    --lr-warmup-samples 5 \
    --min-lr 1e-6 \
    --lr-decay-style cosine \
    --lr-decay-samples 12 \
    --override-lr-scheduler \
    --clip-grad 1.0 \
    --embed-layernorm \
    --weight-decay 1e-1 \
    --fp16 \
    --partition-activations \
    --seed 42 \
    --vocab-file $VOCAB_FILE \
    --merge-file $MERGE_FILE \
    "
OUTPUT_ARGS=" \
    --exit-interval 10 \
    --log-interval 10 \
    --save-interval $SAVE_INTERVAL \
    --eval-interval 100 \
    --eval-iters 10 \
    --checkpoint-activations \
    "

#    --stagger_checkpoint_save_load_group_size 1 \
DATA_ARGS=" \
    --save $CHECKPOINT_PATH \
    --load $CHECKPOINT_PATH \
    --data-path $DATA_PATH \
    --tensorboard-dir $TENSORBOARD_PATH \
    --tensorboard-queue-size 5 \
    --log-timers-to-tensorboard \
    --log-batch-size-to-tensorboard \
    --log-validation-ppl-to-tensorboard \
    --kill-switch-path /tmp/kill-switch \
    "
#    --abort-on-unmet-fused-kernel-constraints \


ZERO_STAGE=1

config_json="./ds_config.json"

# Deepspeed figures out GAS dynamically from dynamic GBS via set_train_batch_size()
cat <<EOT > $config_json
{
  "train_micro_batch_size_per_gpu": $MICRO_BATCH_SIZE,
  "train_batch_size": $GLOBAL_BATCH_SIZE,
  "gradient_clipping": 1.0,
  "zero_optimization": {
    "stage": $ZERO_STAGE
  },
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 500,
    "hysteresis": 2,
    "min_loss_scale": 1,
    "initial_scale_power": 12
  },
  "steps_per_print": 2000,
  "wall_clock_breakdown": false
}
EOT


DEEPSPEED_ARGS=" \
    --deepspeed \
    --deepspeed_config ${config_json} \
    --zero-stage ${ZERO_STAGE} \
    --deepspeed-activation-checkpointing \
    "

ALL_ARGS="$GPT_ARGS $OUTPUT_ARGS $DATA_ARGS $DEEPSPEED_ARGS"

# if you can't stand pt-1.9 launcher noise
export LOGLEVEL=WARNING

PYTHONPATH=/hf/Megatron-DeepSpeed-master

MASTER_ADDR=localhost
MASTER_PORT=6777

export LAUNCHER="deepspeed --num_gpus $N_GPUS --master_port $MASTER_PORT"

export LAUNCHER="python -u -m torch.distributed.run \
    --nproc_per_node $N_GPUS \
    --nnodes 1 \
    --rdzv_endpoint $MASTER_ADDR:$MASTER_PORT \
    --rdzv_backend c10d \
    --max_restarts 0 \
    "

#export CUDA_LAUNCH_BLOCKING=1
export CMD=" \
    env PYTHONPATH=$PYTHONPATH USE_TF=0 \
    $LAUNCHER pretrain_gpt.py \
    --tensor-model-parallel-size $TP_SIZE \
    --pipeline-model-parallel-size $PP_SIZE \
    --distributed-backend nccl \
    $ALL_ARGS \
    "

echo $CMD

$CMD
```

further reduced this to this:
```
`--exit-interval 10`
```
If it's more than 3 there is on crash on exit, w/ 1 or 2 or 3 it crashes.

If I switch to a different launcher the problem goes away, e.g. either of these 2 removes the problem:

```
export LAUNCHER="deepspeed --num_gpus $N_GPUS --master_port $MASTER_PORT"

export LAUNCHER="python -u -m torch.distributed.launch \
    --nproc_per_node $N_GPUS \
    --nnodes 1 \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT \
    "
```

so the problem is specific to c10d

**Comment by stas00** [comment]
Thank you for the feedback, Can!

I was trying to work on this some more, but I happened to update from ubuntu 20.04 to 21.10 2 days ago, and also to pytorch-1.11 and cuda-11.6 on my desktop and at least there it stopped crashing. 

I downgraded back to cuda-11.5 it's still fine, so it's not cuda.

I tried to restore the original environment where it was happening, but for some reason I no longer can use apex built against pt-1.10 reported here https://github.com/NVIDIA/apex/issues/1335

So at the moment on my desktop I can't reproduce it.

The problem still persists on the HPC setup - I need to spend more time trying to derive something reproducible there. It's cuda-11.4 there and pytorch-1.11 w/ cuda-11.5.

**Comment by stas00** [comment]
OK, I figured out how to get pt-.110 working again.

So to update:

pt-1.11 doesn't have this problem, whereas pt-1.10 - do you still want a bug report if pt-1.11 already has it fixed?

If I run with: `CUDA_LAUNCH_BLOCKING=1` now it still crashes:

```
[exiting program at iteration 27] datetime: 2022-03-18 11:31:21 
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: driver shutting down
Exception raised from query at /opt/conda/conda-bld/pytorch_1640811806235/work/aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fd440397d62 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x11a (0x7fd49216666a in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x50 (0x7fd492168960 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x11c (0x7fd49216942c in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #4: <unknown function> + 0xc9039 (0x7fd4ece55039 in /home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #5: <unknown function> + 0x94947 (0x7fd50d85b947 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: clone + 0x44 (0x7fd50d8eba44 in /lib/x86_64-linux-gnu/libc.so.6)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 855813) of binary: /home/stas/anaconda3/envs/py38-pt110/bin/python
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 723, in <module>
    main()
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/stas/anaconda3/envs/py38-pt110/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
pretrain_gpt.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-18_11:31:24
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 855813)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 855813
=======================================================
```

Then on slack you suggested for me to try `export TORCH_DISTRIBUTED_DEBUG=DETAIL` - when I do that - the crash disappears and I get a clean exit.

This sounds like a race condition.

**Comment by cbalioglu** [comment]
In case you don't experience this problem in v1.11, I would just close this issue. Unless it is a very serious bug, we usually avoid backporting fixes to older PyTorch versions and suggest our users to upgrade to the latest version.

**Comment by stas00** [comment]
it turns output buffering off.

e.g.: https://blog.finxter.com/what-is-python-output-buffering-and-how-to-disable-it/

**Comment by treadstone90** [comment]
Can I understand the fix in PyTorch 1.10 ? we do have a barrier call at the end to synchronize how different workers exit. is the fix to allow async exits ?

**Comment by stas00** [comment]
no, the original bug was that I did `sys.exit(msg)` which is not the same as `sys.exit(0)` if that's what you mean, so need to separate the message printing the exiting on non-fatal exit.

**Comment by stas00** [comment]
that one is different, I get it all the time, especially with small models. No idea why, I just started to ignore it. This is happening with pt-1.11 too.

Perhaps @cbalioglu can help, but the difficult part is that for him to help we need to come up with a way to reproduce it w/o Meg-DS.
