### ISSUE TITLE
About reshape deepspeed checkpoint

### ISSUE THREAD

**Issue by henan991201** [bigscience-workshop/Megatron-DeepSpeed#343]
I want to ask why we can not reshape tp and pp to a bigger number? Thanks for any reply.

**Comment by misska1** [comment]
I need to finetune 7B model on V100(32GB)*4 can only use zero_stage 0 and convert transformers into megatron models for TP&PP 4. Looking forward to your work on this  script to increase TP &PP size for Deepspeed checkpoint @stas00

**Comment by stas00** [comment]
Please see:
https://github.com/bigscience-workshop/bigscience/tree/master/train/tr11-176B-ml#checkpoint-reshaping
I know it's not generic at the moment, please let me know if you run into any difficulties following those instructions while adapting to your situation.

@tjruwase, it's probably a good idea to document the topology reshaping process as part of the functionality. Do you have plans to do that? You can totally re-use the steps I shared above. I know you were planning to move all of it into `deepspeed`.

**Comment by tjruwase** [comment]
@stas00, thanks for helping with this issue. Yes, documentation is on my TODO. I think linking to your recipe is a great solution for now.

**Comment by thies1006** [comment]
I tried to create an universal checkpoint of the 3B model (following the instructions in the link) and I get `KeyError: 'param_slice_mappings'`. It seems that this key is created by the BP16 optimizer and (if I'm not mistaken) the 3B model was trained in FP16 format. Is it possible to create the universal checkpoint for those models as well? Thank you! @stas00

**Comment by tjruwase** [comment]
@thies1006, there is ongoing work to support other models. Can you please try the following combination?

Megatron-DeepSpeed: https://github.com/bigscience-workshop/Megatron-DeepSpeed/pull/349
DeepSpeed: https://github.com/microsoft/DeepSpeed/pull/2284

**Comment by thies1006** [comment]
I tried with those PRs and it seems that the problem stays the same.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "ds_to_universal.py", line 108, in extract_zero_shards
    param_slice_mappings = optim_sd[PARAM_SLICE_MAPPINGS]
KeyError: 'param_slice_mappings'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ds_to_universal.py", line 290, in <module>
    main()
  File "ds_to_universal.py", line 269, in main
    _extract_zero_shard_files(args, ds_checkpoint, slice_shapes, temp_dir)
  File "ds_to_universal.py", line 231, in _extract_zero_shard_files
    _do_parallel_work(do_work, work_chunks, args.num_extract_workers)
  File "ds_to_universal.py", line 220, in _do_parallel_work
    pool.map(do_work, batch)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'param_slice_mappings'
```

**Comment by thies1006** [comment]
I'm referring to this model:
https://huggingface.co/bigscience/bloom-3b-optimizer-states/tree/main/global_step337250
I cannot say for sure if this model was trained with Zero 1, maybe @stas00 can confirm?

**Comment by stas00** [comment]
only 176B was trained on A100 and thus bf16, everything else was trained on V100s, thus fp16, thus z1

**Comment by tjruwase** [comment]
Got it. In that case, the model was trained before we started adding universal checkpoint support to z1. Resolving this could require regenerating the checkpoints with the new z1 code. Is this feasible, @stas00?

**Comment by stas00** [comment]
I wasn't part of this training, @TevenLeScao do you by chance know who did the bloom-3b training? and if it's possible to update to the deepspeed@master in the conda env, run one more iteration, save the new checkpoint and update https://huggingface.co/bigscience/bloom-3b-optimizer-states/tree/main/global_step337250?

**Comment by heraclex12** [comment]
Hi, any updates? Does anyone overcome this issue?

**Comment by TevenLeScao** [comment]
Hey, sorry for missing this thread - @stas00 I'm trying that fix.

**Comment by ShinoharaHare** [comment]
Hi, any updates?

**Comment by wptoux** [comment]
I tried to generate a universal checkpoint for bloomz-7b on 8 x a100 40G using the following method.
1. using deepspeed_to_deepspeed.py, convert the data parallel of the checkpoint to 8.
2. in the training code, before starting training, insert the save_checkpoint_and_time(iteration, model, optimizer, lr_scheduler) function so that it can generate a new version of the checkpoint. then load the checkpoint generated in step 1. after The reason for saving the checkpoint before training is that the program will OOM after starting training.
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/e52bdabbde3c6895aceb76c1bced295c2646121f/megatron/training.py#L889
3. use ds_to_universal.py to convert the checkpoint generated in step 2 into a universal checkpoint.

**Comment by LiinXemmon** [comment]
> I tried to generate a universal checkpoint for bloomz-7b on 8 x a100 40G using the following method.
> 
> 1. using deepspeed_to_deepspeed.py, convert the data parallel of the checkpoint to 8.
> 2. in the training code, before starting training, insert the save_checkpoint_and_time(iteration, model, optimizer, lr_scheduler) function so that it can generate a new version of the checkpoint. then load the checkpoint generated in step 1. The reason for saving the checkpoint before training is that the program will OOM after starting training.
>    https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/e52bdabbde3c6895aceb76c1bced295c2646121f/megatron/training.py#L889
> 3. use ds_to_universal.py to convert the checkpoint generated in step 2 into a universal checkpoint.

I am attempting to convert [bigscience/bloom-7b1-optimizer-states](https://huggingface.co/bigscience/bloom-7b1-optimizer-states) to am universal checkpoint. At your step 3, the temp files generated by ds_to_universal.py run out of my 3.5TB disk. Have you met the problem?

**Comment by stas00** [comment]
`7*(8+4)=84` - so you should have a 84GB universal checkpoint. (8+4 optim states+weights)

Can you check with `du -s` where do you get the bloat?

e.g.
```
du -ahd1 /path | sort -rh
```

will help you to sort by large files

**Comment by LiinXemmon** [comment]
> `7*(8+4)=84` - so you should have a 84GB universal checkpoint. (8+4 optim states+weights)
> 
> Can you check with `du -s` where do you get the bloat?
> 
> e.g.
> 
> ```
> du -ahd1 /path | sort -rh
> ```
> 
> will help you to sort by large files

Sorry I did not make it clear.  I first use `deepspeed_to_deepspeed.py` to convert the [bigscience/bloom-7b1-optimizer-states](https://huggingface.co/bigscience/bloom-7b1-optimizer-states) checkpoint into (TP=1,PP=1,DP=1). The converted checkpoint is shown as follows.
![image](https://github.com/bigscience-workshop/Megatron-DeepSpeed/assets/19809646/fe0db70a-2467-4c7d-87ff-0d0555569769)

Then  I load the checkpoint and train for 1 iteration and save the checkpoint. After that I run ds_to_universal.py. I can't see the final universal checkpoint files since at the first stage "Extracting ZeRO fragments" it generates some big files under `/output_folder/tmp/`. The files are like below
![image](https://github.com/bigscience-workshop/Megatron-DeepSpeed/assets/19809646/6c18d58b-416e-41ef-9f23-328d8260f283)
These are only part of them. The total size can be bigger than 3.5TB. I have no idea why they get that big. The converting ends up with "no more disk space". Do I just need a larger ssd or is something wrong?

**Comment by stas00** [comment]
Thank you for the details, @LiinXemmon 

@tjruwase, is it possible we are hitting the tensor bloat here as well? Same as you're fixing in https://github.com/microsoft/DeepSpeed/pull/3348

**Comment by tjruwase** [comment]
@stas00, yes, it is likely the same issue. The outcome of using `torch-checkpoint-shrink.py` would be a useful tip.
