### ISSUE TITLE
  pip install -e . failed with ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by SeekPoint** [bigscience-workshop/Megatron-DeepSpeed#383]
(gh_Megatron-DeepSpeed_yk) ub2004@ub2004-B85M-A0:~/nndev/Megatron-DeepSpeed_yk$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 

(gh_Megatron-DeepSpeed_yk) ub2004@ub2004-B85M-A0:~/nndev/Megatron-DeepSpeed_yk$ pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/ub2004/nndev/Megatron-DeepSpeed_yk
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpt8h0pmfx get_requires_for_build_wheel /tmp/tmp8ag4vfhf
       cwd: /home/ub2004/nndev/Megatron-DeepSpeed_yk
  Complete output (19 lines):
  Traceback (most recent call last):
    File "/tmp/tmpt8h0pmfx", line 280, in <module>
      main()
    File "/tmp/tmpt8h0pmfx", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpt8h0pmfx", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-axg278ny/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-axg278ny/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-axg278ny/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-axg278ny/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 25, in <module>
    File "/home/ub2004/nndev/Megatron-DeepSpeed_yk/megatron/__init__.py", line 15, in <module>
      import torch
  ModuleNotFoundError: No module named 'torch'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpt8h0pmfx get_requires_for_build_wheel /tmp/tmp8ag4vfhf Check the logs for full command output.
(gh_Megatron-DeepSpeed_yk) ub2004@ub2004-B85M-A0:~/nndev/Megatron-DeepSpeed_yk$

**Comment by manestay** [comment]
I have the same issue. I verified that `import torch` works in a python shell from that directoy.

**Comment by Eugene29** [comment]
same.
