### ISSUE TITLE
`PretrainedFromHF` crashes on 1 gpu

### ISSUE THREAD

**Issue by stas00** [bigscience-workshop/Megatron-DeepSpeed#93]
When using `PretrainedFromHF` it seems to require at least 2 gpus and specifically TP=2, otherwise with 1 gpu it crashes

To reproduce:

```
CHECKPOINT_PATH=checkpoints/gpt2
VOCAB_FILE=data/gpt2-vocab.json
MERGE_FILE=data/gpt2-merges.txt
DATA_PATH=data/meg-gpt2_oscar-combined_text_document
TENSORBOARD_PATH=output_dir/tensorboard

TP_SIZE=1
PP_SIZE=1
N_GPUS=1

NLAYERS=24
NHIDDEN=1024
NHEADS=16
FFN_HIDDEN_SIZE=4096
SEQ_LEN=2048


GPT_ARGS=" \
    --exit-interval 10 \
    --num-layers $NLAYERS \
    --hidden-size $NHIDDEN \
    --num-attention-heads $NHEADS \
    --seq-length $SEQ_LEN \
    --max-position-embeddings $SEQ_LEN  \
    --micro-batch-size 2 \
    --rampup-batch-size 4 4 1_000 \
    --global-batch-size 16 \
    --train-samples 100 \
    --optimizer adam \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-8 \
    --lr 1e-4 \
    --lr-warmup-samples 5 \
    --clip-grad 1.0 \
    --weight-decay 1e-1 \
    --fp16 \
    --tensor-model-parallel-size $TP_SIZE \
    --pipeline-model-parallel-size $PP_SIZE \
    --tokenizer-type PretrainedFromHF \
    --tokenizer-name-or-path t5-small \
    "

OUTPUT_ARGS=" \
    --log-interval 10 \
    --save-interval $SAVE_INTERVAL \
    --eval-interval 100 \
    --eval-iters 10 \
    --checkpoint-activations \
    "

DATA_ARGS=" \
    --save $CHECKPOINT_PATH \
    --load $CHECKPOINT_PATH \
    --data-path $DATA_PATH \
    --tensorboard-dir $TENSORBOARD_PATH \
    --tensorboard-queue-size 5 \
    --log-timers-to-tensorboard \
    --log-batch-size-to-tensorboard \
    --log-validation-ppl-to-tensorboard \
    "

ALL_ARGS="$GPT_ARGS $OUTPUT_ARGS $DATA_ARGS"

# if you can't stand pt-1.9 launcher noise
export LOGLEVEL=WARNING

LAUNCHER="deepspeed --num_gpus $N_GPUS"

CMD="$LAUNCHER pretrain_gpt.py $ALL_ARGS"

echo $CMD

#rm -rf $CHECKPOINT_PATH
$CMD

```

It crashes w/ or w/o deepspeed enabled, the above script is w/o deepspeed.

The log:
```
[before the start of training step] datetime: 2021-09-08 17:38:58 
[2021-09-08 17:38:58,791] [INFO] [checkpointing.py:408:forward] Activation Checkpointing Information
[2021-09-08 17:38:58,792] [INFO] [checkpointing.py:409:forward] ----Partition Activations False, CPU CHECKPOINTING False
[2021-09-08 17:38:58,792] [INFO] [checkpointing.py:412:forward] ----contiguous Memory Checkpointing False with 2 total layers
[2021-09-08 17:38:58,792] [INFO] [checkpointing.py:415:forward] ----Synchronization False
[2021-09-08 17:38:58,792] [INFO] [checkpointing.py:416:forward] ----Profiling time in checkpointing False
/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [159,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [159,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [159,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

[...] some 10000 of these [...]

/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [339,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1623448278899/work/aten/src/ATen/native/cuda/Indexing.cu:702: indexSelectLargeIndex: block: [339,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "pretrain_gpt.py", line 222, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 147, in pretrain
    iteration = train(forward_step_func,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 686, in train
    train_step(forward_step_func,
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/training.py", line 387, in train_step
    loss = model[0].train_batch(data_iter=data_iterator)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/engine.py", line 291, in train_batch
    self._exec_schedule(sched)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/engine.py", line 1237, in _exec_schedule
    self._exec_instr(**cmd.kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/engine.py", line 587, in _exec_forward_pass
    outputs = super().forward(inputs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/engine.py", line 1164, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/module.py", line 347, in forward
    x = self.activation_checkpoint_func(
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 690, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 494, in forward
    outputs = run_function(*inputs_cuda)
  File "/mnt/nvme1/code/github/00optimize/deepspeed-big-science/deepspeed/runtime/pipe/module.py", line 325, in exec_func
    inputs = layer(inputs)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/model/transformer.py", line 585, in forward
    return super().forward(hidden_states, attention_mask, **kwargs)
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/model/transformer.py", line 477, in forward
    self.self_attention(layernorm_output,
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/model/transformer.py", line 215, in forward
    mixed_x_layer, _ = self.query_key_value(hidden_states)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/nvme1/code/huggingface/Megatron-DeepSpeed-master/megatron/mpu/layers.py", line 289, in forward
    output_parallel = F.linear(input_parallel, self.weight, bias)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1623448278899/work/c10/cuda/CUDACachingAllocator.cpp:1055 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f99385a7a22 in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10ac3 (0x7f9938809ac3 in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a7 (0x7f993880b167 in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f99385915a4 in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0xa249ba (0x7f99b1e819ba in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xa24a51 (0x7f99b1e81a51 in /home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1932c6 (0x55f7dd66d2c6 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #7: <unknown function> + 0x1592ac (0x55f7dd6332ac in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #8: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #9: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #10: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #11: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #12: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #13: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #14: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #15: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #16: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #17: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #18: <unknown function> + 0x1593ab (0x55f7dd6333ab in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #19: <unknown function> + 0x158e77 (0x55f7dd632e77 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #20: <unknown function> + 0x1590dc (0x55f7dd6330dc in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #21: <unknown function> + 0x1e3643 (0x55f7dd6bd643 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #22: <unknown function> + 0x159109 (0x55f7dd633109 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #23: <unknown function> + 0x1e3643 (0x55f7dd6bd643 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #24: <unknown function> + 0x176057 (0x55f7dd650057 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #25: _PyModule_ClearDict + 0x103 (0x55f7dd687d53 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #26: PyImport_Cleanup + 0x578 (0x55f7dd6aff88 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #27: Py_FinalizeEx + 0x79 (0x55f7dd6e1a49 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #28: Py_RunMain + 0x183 (0x55f7dd6e3893 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #29: Py_BytesMain + 0x39 (0x55f7dd6e3ca9 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
frame #30: __libc_start_main + 0xf3 (0x7f99e84330b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #31: <unknown function> + 0x1e21c7 (0x55f7dd6bc1c7 in /home/stas/anaconda3/envs/py38-pt19/bin/python)
```

It works if I use 2 gpus and TP=2.

Originally discovered by @tjruwase and I was able to reproduce it too. 

We were trying to use the 350m checkpoint you gave us to test the checkpoint conversion tool - so we were unable to use it since the final checkpoint needs to be a single file - 1 gpu.

I also see `PretrainedFromHF` is not being tested. So probably a test is needed as well.

Thank you.

@TevenLeScao

**Comment by sbmaruf** [comment]
Not sure what is the issue,

I could run this following command without any problem, 

```
CHECKPOINT_PATH=dumped/test/

EXP_PATH="./dumped/test/"
mkdir -p $EXP_PATH
BASE_DATA_PATH=$EXP_PATH
INPUT_PATH=$EXP_PATH
OUTPUT_PATH=$EXP_PATH

python scripts/test_multiple_dataset_sampling/create_dummy_dataset.py --dir ${INPUT_PATH}


python tools/preprocess_data.py \
    --input ${INPUT_PATH}/dataset_0.json \
    --output-prefix ${OUTPUT_PATH}/dataset-0 \
    --dataset-impl mmap \
    --tokenizer-type PretrainedFromHF \
    --tokenizer-name-or-path t5-small \
    --append-eod

CHECKPOINT_PATH=dumped/test/
DATA_PATH=dumped/test/dataset-0_text_document
TENSORBOARD_PATH=dumped/test/

TP_SIZE=1
PP_SIZE=1
N_GPUS=1
SAVE_INTERVAL=100

NLAYERS=24
NHIDDEN=1024
NHEADS=16
FFN_HIDDEN_SIZE=4096
SEQ_LEN=2048


GPT_ARGS=" \
    --exit-interval 10 \
    --num-layers $NLAYERS \
    --hidden-size $NHIDDEN \
    --num-attention-heads $NHEADS \
    --seq-length $SEQ_LEN \
    --max-position-embeddings $SEQ_LEN  \
    --micro-batch-size 2 \
    --rampup-batch-size 4 4 1_000 \
    --global-batch-size 16 \
    --train-samples 100 \
    --optimizer adam \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-8 \
    --lr 1e-4 \
    --lr-warmup-samples 5 \
    --clip-grad 1.0 \
    --weight-decay 1e-1 \
    --fp16 \
    --tensor-model-parallel-size $TP_SIZE \
    --pipeline-model-parallel-size $PP_SIZE \
    --tokenizer-type PretrainedFromHF \
    --tokenizer-name-or-path t5-small \
    "


OUTPUT_ARGS=" \
    --log-interval 10 \
    --save-interval $SAVE_INTERVAL \
    --eval-interval 100 \
    --eval-iters 10 \
    --checkpoint-activations \
    "

DATA_ARGS=" \
    --save $CHECKPOINT_PATH \
    --load $CHECKPOINT_PATH \
    --data-path $DATA_PATH \
    --tensorboard-dir $TENSORBOARD_PATH \
    --tensorboard-queue-size 5 \
    --log-timers-to-tensorboard \
    --log-batch-size-to-tensorboard \
    --log-validation-ppl-to-tensorboard \
    "

ALL_ARGS="$GPT_ARGS $OUTPUT_ARGS $DATA_ARGS"

# if you can't stand pt-1.9 launcher noise
export LOGLEVEL=WARNING

LAUNCHER="deepspeed --num_gpus $N_GPUS"

CMD="$LAUNCHER pretrain_gpt.py $ALL_ARGS"

echo $CMD

#rm -rf $CHECKPOINT_PATH
$CMD
```

Can you make sure that your dataset `data/meg-gpt2_oscar-combined_text_document` is tokenized with  `t5-small` ?

@stas00

**Comment by stas00** [comment]
Thank you, @sbmaruf 

Indeed the dataset used for that experiment wasn't made with t5. Yet it works just fine with TP=2 and higher, which is super-odd.

Any suggestions at detection of such mismatches? Should we somehow extend the dataset to mark which tokenizer it was created with and assert if a mismatch was detected?

**Comment by thomasw21** [comment]
Closing as this seems outdated.
